import Header from "@/components/layout/Header";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"],weight:['400', '500', '700'] });

export const metadata = {
  title: "Mairaj Food APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    

      <body className={roboto.className}>
    
       <main className="max-w-4xl w-full mx-auto p-4">
       <Header/>
       {children}
       </main>
        </body>
    </html>
  );
}
